# Generated by Django 2.1.3 on 2018-11-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
